### PR TITLE
Not completed... struggling

### PR DESCRIPTION
**Pull request by isabelra1**

### CODE REVIEW

**Comment by eriqande** [comment]
Hi Isabel,

You got a pull request submitted, which is pretty awesome!  

Do you have time during my office hours on Wednesday from 10 to 11:30?  It would be great to meet to get you on the right track on this assignment.

If not, we could set up another time.  I suspect it is just a full little things you are getting caught on with this assignment, and it would be great get those cleared up soon.  Just let me know what times could work for you, if not my office hours.

Cheers,

eric

**Comment by isabelra1** [comment]
Hi Eric! Thank you for reaching out, I would love to get together so I can really understand this assignment. I have a lab and then honors seminar during your office hours on Wednesdays so unfortunately that time doesn't work for me. My Wednesdays are pretty busy, but do you have any time on Thursday before class? Or after 2:30pm on Thursday?

**Comment by eriqande** [comment]
OK.  Let's meet at 9 AM in the NE corner of 3rd floor bio.  I sent a google
calendar invite, too.

Cheers,

eric

**Comment by isabelra1** [comment]
Sounds good, thank you again!

**Comment by isabelra1** [comment]
Thanks for your help!

**Comment by eriqande** [comment]
You are welcome!  I'm glad that we got to work through this.  Great job.

**Pull request closed without merging**
