### PR TITLE
008 more snake

### PR DESCRIPTION
**Pull request by lilyd-csu**
Hey Eric,

*Update 4/12:* I ran the snakefile, but weirdly the new rules I added for assignment 8 didn't seem to run. I also have pushed up my log file, which shows where the script stopped running. Do you know why this could be?

Thanks, and enjoy your weekend!

--
I'm so sorry this is so late!! I have *finally* finished adding the rules to my Snakefile, but unfortunately, I am getting an error when trying to run it:

SyntaxError in file /projects/ldurkee@colostate.edu/con-gen-csu/assignments/008-hard-filter-gatk-vcfs/Snakefile, line 182:
Command must be given as string after the shell keyword.:
None

I went to this spot in the script, and have checked my use of quotes/spaces/tabs (I always use double quotes, there are no tabs) and can't figure out what the error is referring to. Is it essential that this script runs for the next steps in class?

Thanks!
--Lily

### CODE REVIEW

**Comment by eriqande** [comment]
Hey Lily!

It looks like you may not have committed any of your files from the 008-more-snake homework to this branch.  If you do that---and be sure to have all the files you need for the homework---then I can check it out and see what is going on.

It would be good to get this to run.  

Cool!

**Comment by eriqande** [comment]
Hey Lily,

You had two instance of the hard_filter_indels rule in there.  The first of which you had edited and it had double quotes inside  of double quotes.  You can delete that first edited instance of that rule.  

Then, you need to add something like
```yaml
      snps:
        - ' -filter "QD < 2.0" --filter-name "QD2" '
        - ' -filter "QUAL < 30.0" --filter-name "QUAL30" '
        - ' -filter "SOR > 3.0" --filter-name "SOR3" '
        - ' -filter "FS > 60.0" --filter-name "FS60" '
        - ' -filter "MQ < 40.0" --filter-name "MQ40" '
        - ' -filter "MQRankSum < -12.5" --filter-name "MQRankSum-12.5" '
        - ' -filter "ReadPosRankSum < -8.0" --filter-name "ReadPosRankSum-8" '

```
[Snakefile.txt](https://github.com/eriqande/con-gen-csu/files/14963279/Snakefile.txt)
[config.yaml.txt](https://github.com/eriqande/con-gen-csu/files/14963282/config.yaml.txt)

to the config.yaml file.  after that it did a dry run just fine.

I am attaching versions of the Snakefile and the config.yaml that I fixed. (I had to add the txt extension to get GitHub to accept them as uploads).

**Comment by lilyd-csu** [comment]
Oh my gosh, thanks so much Eric!! I’ll try it later this afternoon!
________________________________

**Comment by lilyd-csu** [comment]
> Hey Eric,
> 
> _Update 4/12:_ I ran the snakefile, but weirdly the new rules I added for assignment 8 didn't seem to run. I also have pushed up my log file, which shows where the script stopped running. Do you know why this could be?
> 
> Thanks, and enjoy your weekend!
> 
> -- I'm so sorry this is so late!! I have _finally_ finished adding the rules to my Snakefile, but unfortunately, I am getting an error when trying to run it:
> 
> SyntaxError in file /projects/[ldurkee@colostate.edu](mailto:ldurkee@colostate.edu)/con-gen-csu/assignments/008-hard-filter-gatk-vcfs/Snakefile, line 182: Command must be given as string after the shell keyword.: None
> 
> I went to this spot in the script, and have checked my use of quotes/spaces/tabs (I always use double quotes, there are no tabs) and can't figure out what the error is referring to. Is it essential that this script runs for the next steps in class?
> 
> Thanks! --Lily

I fixed it! I forgot to update rule all. Thanks for all of your help, Eric!

**Comment by lilyd-csu** [comment]
> > Hey Eric,
> > _Update 4/12:_ I ran the snakefile, but weirdly the new rules I added for assignment 8 didn't seem to run. I also have pushed up my log file, which shows where the script stopped running. Do you know why this could be?
> > Thanks, and enjoy your weekend!
> > -- I'm so sorry this is so late!! I have _finally_ finished adding the rules to my Snakefile, but unfortunately, I am getting an error when trying to run it:
> > SyntaxError in file /projects/[ldurkee@colostate.edu](mailto:ldurkee@colostate.edu)/con-gen-csu/assignments/008-hard-filter-gatk-vcfs/Snakefile, line 182: Command must be given as string after the shell keyword.: None
> > I went to this spot in the script, and have checked my use of quotes/spaces/tabs (I always use double quotes, there are no tabs) and can't figure out what the error is referring to. Is it essential that this script runs for the next steps in class?
> > Thanks! --Lily
> 
> I fixed it! I forgot to update rule all. Thanks for all of your help, Eric!

I've committed all.log in addition to all.vcf.stats, because all.vcf.stats was blank. Does this look correct?

**Comment by eriqande** [comment]
Excellent!

**Pull request closed without merging**
