### PR TITLE
Fastp iteration

### PR DESCRIPTION
**Pull request by bwavila**
I would love to have a chat about the SAMPLES line.  I got it to do what I wanted, however, I spent more time searching for a way to get basename to let me glob a wildcard than anything else.  I finally just ended up brute force coding it.  I bet there is a more elegant way to do it.

### CODE REVIEW

**Comment by eriqande** [comment]
Hey Brian!

It looks like your SAMPLES might not contain anything.  Try just globbing the _R1_ files.  You only need each name once, which is what you get with `data/fastqs/DPCh_plate1_*R1*`.  So:

```
SAMPLES=$(basename -s _R1.fq.gz -a  data/fastqs/DPCh_plate1_*R1*)
```

Give that a whirl and push up the updated SHA1's.

**Comment by bwavila** [comment]
REALLY!?  I even tested it.  I wonder what happened... I will test it again.

**Comment by bwavila** [comment]
Fixed it.  Found the problem from going from my test to the homework.  Thank you!

**Comment by eriqande** [comment]
Nice!  That is all working now.

**Pull request closed without merging**
